<a href="https://colab.research.google.com/github/mananmalvi/ML--The-Art/blob/main/DAY_6_Forest_Cover_Type_Pred(Random_Forest_Basic_Project).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# This ML Project is for - FOREST COVER TYPE PREDICTION
# taking inputs from the input of forest details and predicting the type of forest
# meaning of some features in data-
# Topographic Features
""" Elevation: The height of the plot in meters above sea level. It is often the most influential predictor of tree species because it correlates with temperature and oxygen levels.
Aspect: The compass direction that a slope faces (0 to 360 degrees). For example, 0° is North, 90° is East, 180° is South, and 270° is West.
Slope: The steepness or incline of the land, measured in degrees. It affects how water drains and how much soil stays in place.

Distance Features
Horizontal Distance to Hydrology: The flat, straight-line distance (in meters) to the nearest surface water like a stream or lake.
Vertical Distance to Hydrology: The elevation difference (vertical height change) between the plot and the nearest surface water.
Horizontal Distance to Roadways: The distance from the plot to the nearest public road, which can indicate human impact or accessibility.

Distance Features
Horizontal Distance to Hydrology: The flat, straight-line distance (in meters) to the nearest surface water like a stream or lake.
Vertical Distance to Hydrology: The elevation difference (vertical height change) between the plot and the nearest surface water.
Horizontal Distance to Roadways: The distance from the plot to the nearest public road, which can indicate human impact or accessibility. """

' Elevation: The height of the plot in meters above sea level. It is often the most influential predictor of tree species because it correlates with temperature and oxygen levels.\nAspect: The compass direction that a slope faces (0 to 360 degrees). For example, 0° is North, 90° is East, 180° is South, and 270° is West.\nSlope: The steepness or incline of the land, measured in degrees. It affects how water drains and how much soil stays in place.\n\nDistance Features\nHorizontal Distance to Hydrology: The flat, straight-line distance (in meters) to the nearest surface water like a stream or lake.\nVertical Distance to Hydrology: The elevation difference (vertical height change) between the plot and the nearest surface water.\nHorizontal Distance to Roadways: The distance from the plot to the nearest public road, which can indicate human impact or accessibility.\n\nDistance Features\nHorizontal Distance to Hydrology: The flat, straight-line distance (in meters) to the nearest surface wa

In [ ]:
import pandas as pd
import numpy as np

In [ ]:
df = pd.read_csv("/content/train.csv")

In [ ]:
df.head()

,Id,Elevation,Aspect,Slope,Horizontal_Distance_To_Hydrology,Vertical_Distance_To_Hydrology,Horizontal_Distance_To_Roadways,Hillshade_9am,Hillshade_Noon,Hillshade_3pm,...,Soil_Type32,Soil_Type33,Soil_Type34,Soil_Type35,Soil_Type36,Soil_Type37,Soil_Type38,Soil_Type39,Soil_Type40,Cover_Type
0,1,2596,51,3,258,0,510,221,232,148,...,0,0,0,0,0,0,0,0,0,5
1,2,2590,56,2,212,-6,390,220,235,151,...,0,0,0,0,0,0,0,0,0,5
2,3,2804,139,9,268,65,3180,234,238,135,...,0,0,0,0,0,0,0,0,0,2
3,4,2785,155,18,242,118,3090,238,238,122,...,0,0,0,0,0,0,0,0,0,2
4,5,2595,45,2,153,-1,391,220,234,150,...,0,0,0,0,0,0,0,0,0,5


In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15120 entries, 0 to 15119
Data columns (total 56 columns):
 #   Column                              Non-Null Count  Dtype
---  ------                              --------------  -----
 0   Id                                  15120 non-null  int64
 1   Elevation                           15120 non-null  int64
 2   Aspect                              15120 non-null  int64
 3   Slope                               15120 non-null  int64
 4   Horizontal_Distance_To_Hydrology    15120 non-null  int64
 5   Vertical_Distance_To_Hydrology      15120 non-null  int64
 6   Horizontal_Distance_To_Roadways     15120 non-null  int64
 7   Hillshade_9am                       15120 non-null  int64
 8   Hillshade_Noon                      15120 non-null  int64
 9   Hillshade_3pm                       15120 non-null  int64
 10  Horizontal_Distance_To_Fire_Points  15120 non-null  int64
 11  Wilderness_Area1                    15120 non-null  int64
 12  Wild

In [ ]:
df['Cover_Type'].value_counts() # this is our prediction or output

,count
Cover_Type,
5,2160
2,2160
1,2160
7,2160
3,2160
6,2160
4,2160


In [ ]:
x = df.drop('Cover_Type',axis=1)
y = df['Cover_Type']

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train,y_test= train_test_split(x,y,test_size=0.2, random_state=42)

In [ ]:
x_train.shape

(12096, 55)

In [ ]:
x_test.shape

(3024, 55)

In [ ]:
# selecting best from multiples model ,

In [ ]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
log= LogisticRegression()
log.fit(x_train,y_train)
y_pred = log.predict(x_test)

accuracy_score(y_test,y_pred)*100

/usr/local/lib/python3.12/dist-packages/sklearn/linear_model/_logistic.py:465: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


38.26058201058201

In [ ]:
from sklearn.tree import DecisionTreeClassifier
dtc= DecisionTreeClassifier()
dtc.fit(x_train,y_train)
y_pred = dtc.predict(x_test)

accuracy_score(y_test,y_pred)*100

81.28306878306879

In [ ]:
from sklearn.ensemble import RandomForestClassifier
rfc= RandomForestClassifier()
rfc.fit(x_train,y_train)
y_pred = rfc.predict(x_test)

accuracy_score(y_test,y_pred)*100

87.86375661375662

In [ ]:
df["Cover_Type"].value_counts()

,count
Cover_Type,
5,2160
2,2160
1,2160
7,2160
3,2160
6,2160
4,2160


In [ ]:
df.iloc[10].values # features values from 10th row

array([  11, 2612,  201,    4,  180,   51,  735,  218,  243,  161, 6222,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          5])

In [ ]:
user_input = (11, 2612,  201,    4,  180,   51,  735,  218,  243,  161, 6222,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          5)

In [ ]:
features= np.array([user_input])

In [ ]:
rfc.predict(np.array([user_input[:-1]])).reshape(1,-1)
rfc.predict(np.array([user_input[:-1]])).reshape(1,-1)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[5]])

In [ ]:
df.iloc[100].values

array([ 101, 2998,   45,    8,  351,   16, 5842,  223,  222,  134, 3721,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          2])

In [ ]:
user_input1=(101, 2998,   45,    8,  351,   16, 5842,  223,  222,  134, 3721,
          1,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    1,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          2)

In [ ]:
features= np.array([user_input1])

In [ ]:
rfc.predict(np.array([user_input1[:-1]])).reshape(1,-1)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but RandomForestClassifier was fitted with feature names
  warnings.warn(


array([[2]])

In [ ]:
import pickle
pickle.dump(rfc,open('rfc.pkl','wb'))